blueprints/api.py
from flask import Blueprint, jsonify, make_response, request, send_file
from core.viewmodel import MeterViewModel, JournalViewModel
from .auth import requires_auth


api = Blueprint('api', __name__)


@api.route('/api/meter')
@requires_auth
def meters(uid):
    _meters = MeterViewModel(user_id=uid).get()
    return jsonify(_meters)


@api.route('/api/meter', methods=['POST'])
@requires_auth
def add_meter(uid):
    _name = request.form.get('name')
    try:
        return jsonify({
            'id': MeterViewModel(user_id=uid).save(name=_name)
        })
    except (TypeError, ValueError):
        return make_response(jsonify({}), 404)


@api.route('/api/meter', methods=['DELETE'])
@requires_auth
def delete_meter(uid):
    try:
        _meter_id = request.form.get('meter_id')
        return jsonify({
            'id': MeterViewModel(user_id=uid).delete(_meter_id)
        })
    except (TypeError, ValueError):
        return make_response(jsonify({}), 404)


@api.route('/api/meter/<int:meter_id>/index', methods=['POST'])
@requires_auth
def add_index(uid, meter_id):
    try:
        _date = request.form.get('date')
        _value = float(request.form.get('value'))
        return jsonify({
            'id': JournalViewModel(user_id=uid, meter_id=meter_id).save_index(_date, _value)
        })
    except (TypeError, ValueError):
        make_response(jsonify({}), 404)


@api.route('/api/meter/<int:meter_id>/index', methods=['DELETE'])
@requires_auth
def delete_index(uid, meter_id):
    try:
        _index_id = int(request.form.get('index_id'))
        return jsonify({
            'id': JournalViewModel(user_id=uid, meter_id=meter_id).delete_index(_index_id)
        })
    except (TypeError, ValueError):
        make_response(jsonify({}), 404)


@api.route('/api/meter/<int:meter_id>/journal')
@requires_auth
def journal(uid, meter_id):
    try:
        return jsonify(JournalViewModel(user_id=uid, meter_id=meter_id).get())
    except (TypeError, ValueError):
        return make_response(jsonify({}), 404)


@api.route('/api/meter/<int:meter_id>/journal/export')
@requires_auth
def export_journal(uid, meter_id):
    try:
        filename = JournalViewModel(user_id=uid, meter_id=meter_id).export_csv()
        return send_file(filename,
                         mimetype="text/csv",
                         as_attachment=True,
                         attachment_filename="export.csv")
    except (TypeError, ValueError):
        return make_response(jsonify({}), 404)


@api.route('/api/meter/<int:meter_id>/journal/import', methods=['POST'])
@requires_auth
def import_journal(uid, meter_id):
    try:
        if 'file' not in request.files:
            return make_response(jsonify({}), 400)
        file = request.files['file']
        if file.filename == '':
            return make_response(jsonify({}), 400)
        _journal = JournalViewModel(user_id=uid, meter_id=meter_id)
        if _journal is not None:
            _journal.import_csv(file)
        else:
            return make_response(jsonify({}), 404)
    except:
        return make_response(jsonify({}), 500)

    return make_response(jsonify({}), 200)

blueprints/auth.py
import os
from urllib.parse import urlencode
from urllib.request import urlopen
from functools import wraps
import jwt
import json
from flask import Blueprint, request, redirect, session, url_for, make_response, jsonify, current_app
from authlib.integrations.flask_client import OAuth


auth = Blueprint('auth', __name__)
oauth = OAuth(current_app)
auth0 = oauth.register(
    'auth0',
    client_id=os.environ['AUTH0_CLIENT_ID'],
    client_secret=os.environ['AUTH0_CLIENT_SECRET'],
    api_base_url='https://asgaror.eu.auth0.com',
    access_token_url='https://asgaror.eu.auth0.com/oauth/token',
    authorize_url='https://asgaror.eu.auth0.com/authorize',
    client_kwargs={
        'scope': 'openid profile',
    },
)


@auth.route('/login')
def login():
    if os.environ['FLASK_ENV'] == 'development':
        session['profile'] = {
            'id': 'auth0|6ca2578067456311c2de32be',
            'email': 'dev@asgaror.space'
        }
        return redirect(url_for('view.index'))
    return auth0.authorize_redirect(
        redirect_uri="{}{}".format(request.url_root[0:-1], '/authorize'),
        audience='https://asgaror.eu.auth0.com/userinfo')


@auth.route('/logout')
def logout():
    session.clear()
    if os.environ['FLASK_ENV'] == 'development':
        return redirect(url_for('view.login'))
    params = {'returnTo': url_for('view.index', _external=True),
              'client_id': os.environ['AUTH0_CLIENT_ID']}
    return redirect(auth0.api_base_url + '/v2/logout?' + urlencode(params))


@auth.route('/authorize')
def authorize():
    # Handles response from token endpoint
    auth0.authorize_access_token()
    resp = auth0.get('userinfo')
    userinfo = resp.json()

    # Store the user information in flask session.
    session['jwt_payload'] = userinfo
    session['profile'] = {
        'id': userinfo['sub'],
        'email': userinfo['name'],
        'all': userinfo,
    }
    return redirect(url_for('view.index'))


def get_auth_token():
    auth_header = request.headers.get("Authorization", None)
    if auth_header:
        if auth_header.split()[0].lower() == "bearer":
            return auth_header.split()[1]
    return None


def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        # If regular user access...
        if 'profile' in session:
            return f(*args, uid=session['profile']['id'], **kwargs)
        # If client auth
        token = get_auth_token()
        #marche pas ici...
        if token is None:
            return redirect(url_for('auth.login'))
        unverified_token = jwt.get_unverified_header(token)
        jwksurl = urlopen('https://asgaror.eu.auth0.com/.well-known/jwks.json')
        jwks = json.loads(jwksurl.read())

        public_keys = {}
        for jwk in jwks['keys']:
            kid = jwk['kid']
            public_keys[kid] = jwt.algorithms.RSAAlgorithm.from_jwk(json.dumps(jwk))
        kid = unverified_token['kid']
        key = public_keys[kid]

        if public_keys:
            try:
                payload = jwt.decode(token, key=key, algorithms=['RS256'], audience='powermeter-api')
                session['profile']['token'] = payload
                return f(*args, uid=payload, **kwargs)
            except:
                return make_response(jsonify({}), 401)

    return decorated


def requires_scopes(scopes):
    def call(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            token = get_auth_token()
            if token is not None:
                claims = jwt.decode(token, verify=False)
            elif session.get('jwt_payload') is not None:
                claims = session['jwt_payload'].get('scope')
            else:
                return f'A token is needed...'

            if claims is not None:
                token_scopes = claims['scope'].split()
                for scope in scopes:
                    if scope not in token_scopes:
                        return f'Scope : \'{scope}\' needed !'
            else:
                return f'A scope is needed...'

            return f(*args, **kwargs)
        return decorated
    return call

blueprints/view.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from core.viewmodel import MeterViewModel, JournalViewModel
from .auth import requires_auth


view = Blueprint('view', __name__)


@view.route('/')
@requires_auth
def index(uid):
    index_view_model = MeterViewModel(user_id=uid).get()
    return render_template('index.html.j2', model=index_view_model)


@view.route('/meter', methods=['POST'])
@requires_auth
def add_meter(uid):
    try:
        _name = request.form.get('name')
        _id = MeterViewModel(uid).save(_name)
        return redirect(url_for('view.meter', meter_id=_id))
    except (TypeError, ValueError) as err:
        flash(f"Error : {err}")
        return redirect(url_for('view.index'))


@view.route('/meter/delete', methods=['POST'])
@requires_auth
def delete_meter(uid):
    _meter_id = int(request.form.get('meter-id'))
    MeterViewModel(uid).delete(_meter_id)
    return redirect(url_for('view.index'))


@view.route('/meter/<int:meter_id>')
@requires_auth
def meter(uid, meter_id):
    journal_view_model = JournalViewModel(user_id=uid, meter_id=meter_id).get()
    return render_template('view.html.j2', model=journal_view_model)


@view.route('/meter/<int:meter_id>', methods=['POST'])
@requires_auth
def add_index(uid, meter_id):
    try:
        _value = float(request.form.get('value'))
        _date = request.form.get('date')
        JournalViewModel(user_id=uid, meter_id=meter_id).save_index(_value, _date)
    except (TypeError, ValueError) as err:
        flash(f"Error : {err}")
    finally:
        return redirect(url_for('view.meter', meter_id=meter_id))


@view.route('/meter/<int:meter_id>/delete', methods=['POST'])
@requires_auth
def delete_index(uid, meter_id):
    try:
        _index_id = int(request.form.get('index-id'))
        JournalViewModel(user_id=uid, meter_id=meter_id).delete_index(_index_id)
    except (TypeError, ValueError) as err:
        flash(f"Error : {err}")
    finally:
        return redirect(url_for('view.meter', meter_id=meter_id))

templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="/static/192.png" sizes="192x192">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/bootstrap-style.css">
    <link rel="manifest" href="/static/powermeter.webmanifest">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
    <title>{{ title }}</title>
    {% block head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      {% if model.meter_name is defined %}}
      <a class="navbar-brand" href="{{ url_for('view.index') }}">Back : {{ model.meter_name }}</a>
      {% else %}}
      <a class="navbar-brand" href="{{ url_for('view.index') }}">PowerMeter</a>
      {% endif %}}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <span class="navbar-text ml-auto">
          {% if 'profile' in session %}
            {{ session['profile']['email'] }} (<a href="{{ url_for('auth.logout') }}">logout</a>)
          {% else %}
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          {% endif %}
        </span>
      </div>
    </nav>
    <div class="container-fluid full-height">
      <div class="row">
        <div class="col">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-danger">{{ message }}</div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
          navigator.serviceWorker.register('/static/service-worker.js')
            .then(function(registration) {
              // Registration was successful
              console.log('ServiceWorker registration successful with scope: ', registration.scope);
            }, function(err) {
              // registration failed :(
              console.log('ServiceWorker registration failed: ', err);
            });
        });
      }
  </script>
  </body>
</html>

templates/graph.html.j2
<select id="groupBySelect">
    <option value="default">Don't group</option>
    <option value="year">Year</option>
</select>
<canvas id="myChart"></canvas>

<script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/locale/fr.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8/hammer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@0.7.7/dist/chartjs-plugin-zoom.min.js"></script>
<script src="/static/chart.js"></script>

<script>
  const ctx = document.getElementById("myChart");
  let data = null;
  let chart = null;

  fetch("{{ url_for('api.journal', meter_id=model.meter_id) }}")
  .then((res) => res.json())
  .then((json) => {
    data = json;
    document.getElementById("groupBySelect").dispatchEvent(new Event('change'));
  });

  $("#groupBySelect").on('change', function(e) {
    if (chart) chart.destroy();
    switch(e.target.value) {
      case 'year':
        groupByYear(data).then((journal) => {
          chart = buildChart(ctx, journal)
        }).catch((err)=>console.log(err));
        break;
      default:
        formatForChart(data).then((journal) => {
          chart = buildChart(ctx, journal)
        }).catch((err)=>console.log(err));
    }
  });
</script>

templates/index.html.j2
{% extends "base.html.j2" %}
{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/fr.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
{% endblock %}
{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h4>Meter list</h4>
      </li>
      {% for meter in model %}
      <li class="list-group-item d-flex justify-content-between">
        <span>
          <span class="font-weight-bolder font-italic">#</span>
          <a href="{{ url_for('view.meter', meter_id=meter.id) }}">{{meter.name}}</a>
        </span>
        <button id="btn-modal-delete-meter" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-id="{{ meter.id }}"><span class="font-weight-bolder">X</span></button>
      </li>
      {% endfor %}
      <li class="list-group-item">
        <h4>Add a new meter</h4>
        <form class="form d-flex justify-content-between" action="{{ url_for('view.add_meter') }}" method="POST">
          <input class="form-control" id="name" name="name" type="text" placeholder="Meter name">
          <button class="btn btn-primary btn-sm" type="submit">Create</button>
        </form>
      </li>
    </ul>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete this meter, and all its content ?</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <form action="{{ url_for('view.delete_meter') }}" method="POST">
          <input type="hidden" id="meter-id" name="meter-id" value="">
          <button type="submit" id="confirm-modal" class="btn btn-danger">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  $('#deleteModal').on('show.bs.modal', function (e) {
    document.getElementById('meter-id').value = e.relatedTarget.dataset.id;
  });

  $('#deleteModal').on('hide.bs.modal', function (e) {
    document.getElementById('meter-id').value = '';
  });
</script>
{% endblock %}

templates/list.html.j2
<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th scope="col">Period mean</th>
      <th scope="col">Date</th>
      <th scope="col">Index</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for index in model.entries|reverse %}
        <tr>
          <td>{{ index.mean_consumption_per_day }}</td>
          <td>{{ index.date }}</td>
          <td>{{ index.value }}</td>
          <td>
            <form action="{{ url_for('view.delete_index', meter_id=model.meter_id) }}" method="POST">
              <input type="hidden" name="index-id" value="{{ index.id }}">
              <button type="submit" class="btn btn-sm btn-danger">X</button>
            </form>
          </td>
        </tr>
    {% endfor %}
  </tbody>
</table>

templates/mrs.html.j2
{% extends "base.html.j2" %}
{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/fr.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
{% endblock %}
{% block content %}
  <div class="row" style="height: calc(100vh - 100px); overflow: scroll">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Date</th>
          <th>Reading (KWh)</th>
          <th>Consumption (KWh / day)</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <form action="{{ url_for('mrs') }}" method="POST">
            <th>
              <input class="form-control" id="date" name="date" type="date" placeholder="Date">
            </th>
            <th><input class="form-control" id="value" name="value" type="text" placeholder="Value"></th>
            <th></th>
            <th><button class="btn btn-primary btn-sm" type="submit">Submit</button></th>
          </form>
        </tr>

        {% for mr in mrs %}
          <tr>
            <th>{{mr.date}}</th>
            <th>{{mr.value}}</th>
            <th>{{mr.mean_consumption_per_day}}</th>
            <th><a class="btn btn-danger btn-sm" href="{{ url_for('delete_mr', id=mr.id) }}">X</a></th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row">
    <caption>Mean : {{mean}} KWh / day</caption>
  </div>
  <script>
    document.getElementById('date').valueAsDate = new Date();
  </script>
{% endblock %}

templates/side.html.j2
<div class="d-flex flex-column h-100">
<div class="d-flex flex-column justify-content-between flex-grow-1">
    <ul class="list-group mt-5">
        <li class="list-group-item d-flex justify-content-between active">Stats for this meter</li>
        <li class="list-group-item d-flex justify-content-between">Mean (1 year)<span><strong>{{ model.mean }} KWh</strong></span></li>
        <li class="list-group-item d-flex justify-content-between">Annual projection<span><strong>{{ "{0:.2f}".format(model.mean * 365) }} KWh</strong></span></li>
        <li class="list-group-item d-flex justify-content-between">Trend of the last {{ model.days }} days<span><strong>{{ model.trend_last_days }}</strong></span></li>
    </ul>
    <ul class="list-group" style="margin-bottom: 8px">
        <li class="list-group-item">
            <form action="{{ url_for('view.add_index', meter_id=model.meter_id) }}" method="POST">
                <div class="form-row">
                    <div class="col-9">
                    <input class="form-control form-control-sm" id="date" name="date" type="date" placeholder="Date">
                    <input class="form-control form-control-sm" id="value" name="value" type="text" placeholder="Value">
                    </div>
                    <div class="col-3">
                    <button class="btn btn-primary btn-sm" type="submit" style="width: 100%; height: 100%; font-size: 24px">+</button>
                    </div>
                </div>
            </form>
            <button id="btn-modal-csv "class="btn btn-primary btn-block mt-2"
              data-toggle="modal"
              data-target="#importModal">Import from .csv file</button>
            
            <!-- Modal -->
            <div class="modal fade" id="importModal" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Import a .csv file...</h5>
                    <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form id="confirm-modal-csv">
                      <input id="file" name="file" type="file" accept="text/csv">
                      <input class="btn btn-primary" type="submit" value="Import file">
                    </form>
                </div>
                </div>
            </div>
            </div>
        </li>
    </ul>
</div>
</div>
<script>
  // Set date to today
  document.getElementById('date').valueAsDate = new Date();
  document.getElementById('value').focus();

  // Handle POST of the csv file
  document.getElementById('confirm-modal-csv').addEventListener('submit', postCSV);
  function postCSV(event) {
    event.preventDefault();
    const formData = new FormData();
    const file = document.getElementById('file');
    formData.append('file', file.files[0]);

    fetch("{{ url_for('api.import_journal', meter_id=model.meter_id) }}", {
        method: 'POST',
        body: formData
    }).then((res) => res.json())
    .then((data) => $("#importModal").modal("hide"))
    .catch((err)=>console.log(err))
  }
</script>

templates/template-upload.html.j2
<form action="{{ url_for('import_csv', meter_id=meter_id) }}" enctype="multipart/form-data" method="POST">
    <input name="file" type="file" accept="text/csv">
    <input type="submit" value="Import">
  </form>

templates/view.html.j2
{% extends "base.html.j2" %}
{% block content %}
<div class="row">
  <div class="col-12 col-lg-9">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs d-none d-sm-flex" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="graph-tab" data-toggle="tab" href="#graph" role="tab" aria-controls="graph" aria-selected="true">Graph</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="list-tab" data-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="false">List</a>
      </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content h-100" id="myTabContent">
      <div class="tab-pane tab-height active tab-mobile" id="graph" role="tabpanel" aria-labelledby="graph-tab">
        {% include 'graph.html.j2' %}
      </div>
      <div class="tab-pane tab-height overflow-auto" id="list" role="tabpanel" aria-labelledby="list-tab">
        {% include "list.html.j2" %}  
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-3">
    {% include 'side.html.j2' %}
  </div>
</div>
<div class="row d-block d-sm-none">
  <div class="col">
    <nav class="navbar navbar-light bg-light fixed-bottom" style="margin-bottom: 0">
      <div class="navbar-expand">
        <ul id="bottom-nav" class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#graph">Graph</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#list">List</a>
          </li>
        </ul>
      </div>
    </nav> 
  </div>
</div>
<script>
$('#bottom-nav').click(function (e) {
  e.preventDefault();
  $(`#myTab a[href="#${e.target.href.split('#')[1]}"]`).tab('show');
});
</script>
{% endblock %}